#%RAML 0.8
title: tokenreader
version: 1.0.0
baseUri: http://server/api/{version}
/token:
  get:
    queryParameters:
      user:
        displayName: User Id
        type: string
        description: the user's token
        required: true
      duration:
        displayName: Duration
        type: string
        description: a specified duration, not necessary
        required: false
    responses:
      200:
        body:
          application/json:
            schema: token
            example: |
               {
                  "data":true
                  "success": true,
                  "status": 200
               }
schemas:
 - token: |
  {
    "type": "object",
    "$schema": "http://json-schema.org/draft-03/schema",
    "id": "http://jsonschema.net",
    "required": true,
    "properties": {
      "songTitle": {
        "type": "string",
        "required": true
      },
      "albumId": {
        "type": "string",
        "required": true,
        "minLength": 36,
        "maxLength": 36
      }
    }
  }